### ISSUE TITLE
UI components out of View

### ISSUE THREAD

**Issue by priyanshnama** [IIITDMJ-OPEN-SOURCE/Technical-Fest#1]
This project is using Material theme 
`Theme.MaterialComponents.DayNight.NoActionBar`
Since there is no Action bar any view such as imageView , DrawerLayout are not properly visible when constraint to top.
Probably because the parent **Constraints Layout** has no upper boundary and merging in notification panel on top.

**Tried** using marginTop but it differs on different types of device.
Below attached is are images for refrence
![Screenshot_1598849360](https://user-images.githubusercontent.com/54625644/91684515-6bc51300-eb75-11ea-8786-9a06cbd05a35.png)

**Comment by kartik-pant-23** [comment]
I am very new to github. And this one was my first repository that i cloned. I ran it on android studio but the build fails saying,
File google-services.json is missing
Please help, i would like to contribute.

**Comment by priyanshnama** [comment]
### hello @kartik-pant-23 
Greetings!!

This issue is solved as of now but we would like to hear from you in the future.
Maybe you could **watch** this repository for any other issues we counter in future.

_closing this issue hereby_

**Comment by kartik-pant-23** [comment]
Thank you!

**Comment by priyanshnama** [comment]
@kartik-pant-23 
you can have a look at the [README.md](https://github.com/IIITDMJ-OPEN-SOURCE/Technical-Fest/blob/master/README.md) to get started for contribution in this project and this [wiki page](https://github.com/IIITDMJ-OPEN-SOURCE/Technical-Fest/wiki/How-to-generate-the-google-services.json-file-and-Integrate-it-with-the-App.) too.
