### ISSUE TITLE
Can we update the readme with screenshots of the current state of the app?

### ISSUE THREAD

**Issue by dino-saurabh** [IIITDMJ-OPEN-SOURCE/Technical-Fest#4]
It will be easy to get aquainted with the current state of the app and start contributing !!

**Comment by priyanshnama** [comment]
@LuGO0 Sure Sir, 
I was about to start documentation as the app has now achieved a basic build.
Will update you till tomorrow.

**Comment by priyanshnama** [comment]
@LuGO0 
**Updated the README.md**
- added Screenshots
- Steps for Starting Contribution.

**Comment by dino-saurabh** [comment]
ohkk shud I close it @priyanshnama ?

**Comment by priyanshnama** [comment]
Yes we can close it now @LuGO0
